/**
 * GET /api/export/pdf?planId=xxx — Server-side PDF export
 *
 * Gated to Creator + Pro only. Free users get a 403.
 * Uses @react-pdf/renderer to generate a styled PDF from plan markdown.
 *
 * Sprint 3, Ticket #17
 */

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { createClient } from "@supabase/supabase-js";
import { renderToBuffer } from "@react-pdf/renderer";
import React from "react";
import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";

// -- PDF Styles --
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  header: {
    marginBottom: 20,
    borderBottom: "2 solid #1D9E75",
    paddingBottom: 10,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#1D9E75",
  },
  subtitle: {
    fontSize: 10,
    color: "#6b7280",
    marginTop: 4,
  },
  section: {
    marginBottom: 12,
  },
  heading: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 6,
    marginTop: 10,
    color: "#1D9E75",
  },
  subheading: {
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 4,
    marginTop: 8,
  },
  paragraph: {
    marginBottom: 6,
    lineHeight: 1.5,
  },
  listItem: {
    marginBottom: 3,
    paddingLeft: 12,
    lineHeight: 1.4,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#9ca3af",
  },
});

// -- PDF Document Component --
function PlanPDF({
  content,
  outputType,
  niche,
  createdAt,
}: {
  content: string;
  outputType: string;
  niche: string;
  createdAt: string;
}) {
  const outputLabel =
    outputType === "calendar"
      ? "Weekly Content Calendar"
      : outputType === "trends"
        ? "Trend Report + Post Ideas"
        : "Full Growth Strategy";

  const lines = content.split("\n");

  return React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      // Header
      React.createElement(
        View,
        { style: styles.header },
        React.createElement(Text, { style: styles.title }, "Wavepilot"),
        React.createElement(
          Text,
          { style: styles.subtitle },
          `${outputLabel} — ${niche} — ${new Date(createdAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`
        )
      ),
      // Content
      React.createElement(
        View,
        null,
        ...lines.map((line, i) => {
          const trimmed = line.trim();

          if (trimmed.startsWith("# ")) {
            return React.createElement(
              Text,
              { key: i, style: styles.heading },
              trimmed.replace(/^#+\s*/, "")
            );
          }
          if (trimmed.startsWith("## ") || trimmed.startsWith("### ")) {
            return React.createElement(
              Text,
              { key: i, style: styles.subheading },
              trimmed.replace(/^#+\s*/, "")
            );
          }
          if (trimmed.startsWith("- ") || trimmed.match(/^\d+\.\s/)) {
            return React.createElement(
              Text,
              { key: i, style: styles.listItem },
              `• ${trimmed.replace(/^[-\d.]+\s*/, "").replace(/\*\*/g, "")}`
            );
          }
          if (trimmed === "" || trimmed === "---") {
            return React.createElement(Text, { key: i, style: { marginBottom: 4 } }, " ");
          }

          return React.createElement(
            Text,
            { key: i, style: styles.paragraph },
            trimmed.replace(/\*\*/g, "")
          );
        })
      ),
      // Footer
      React.createElement(
        Text,
        { style: styles.footer },
        "Generated by Wavepilot — wavepilot.co"
      )
    )
  );
}

export async function GET(request: NextRequest) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized", code: "UNAUTHORIZED" }, { status: 401 });
  }

  const planId = request.nextUrl.searchParams.get("planId");
  if (!planId) {
    return NextResponse.json({ error: "planId is required", code: "MISSING_PLAN_ID" }, { status: 400 });
  }

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    return NextResponse.json({ error: "Server configuration error", code: "CONFIG_ERROR" }, { status: 500 });
  }

  const supabase = createClient(url, key, { auth: { persistSession: false } });

  // Check subscription — PDF is Creator + Pro only
  const { data: sub } = await supabase
    .from("subscriptions")
    .select("plan, status")
    .eq("user_id", userId)
    .single();

  const plan = sub?.status === "active" ? sub.plan : "free";
  if (plan === "free") {
    return NextResponse.json(
      { error: "PDF export requires Creator or Pro plan", code: "UPGRADE_REQUIRED" },
      { status: 403 }
    );
  }

  // Fetch the plan
  const { data: planData, error: planError } = await supabase
    .from("plans")
    .select("content, output_type, niche, created_at")
    .eq("id", planId)
    .eq("user_id", userId)
    .single();

  if (planError || !planData) {
    return NextResponse.json({ error: "Plan not found", code: "NOT_FOUND" }, { status: 404 });
  }

  // Generate PDF
  const pdfBuffer = await renderToBuffer(
    PlanPDF({
      content: planData.content,
      outputType: planData.output_type,
      niche: planData.niche,
      createdAt: planData.created_at,
    })
  );

  return new NextResponse(new Uint8Array(pdfBuffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="wavepilot-${planData.output_type}-${planId.slice(0, 8)}.pdf"`,
    },
  });
}
